// $ANTLR 3.2 Sep 23, 2009 12:02:23 /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g 2010-09-13 18:47:33

/*
 * Generated by ANTLR from net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g
 *
 * Do not modify this file directly.
 *
 */

package net.sf.ictalive.operetta.psdeditor.antlr;


import org.antlr.runtime.*;
import java.util.Stack;
import java.util.List;
import java.util.ArrayList;

public class PSDLexer extends Lexer {
    public static final int T__28=28;
    public static final int T__27=27;
    public static final int T__26=26;
    public static final int T__25=25;
    public static final int T__24=24;
    public static final int T__23=23;
    public static final int OPERATOR=5;
    public static final int T__22=22;
    public static final int T__21=21;
    public static final int T__20=20;
    public static final int NUMBER=6;
    public static final int EOF=-1;
    public static final int T__9=9;
    public static final int T__8=8;
    public static final int T__19=19;
    public static final int WS=7;
    public static final int T__16=16;
    public static final int T__15=15;
    public static final int T__18=18;
    public static final int T__17=17;
    public static final int T__12=12;
    public static final int T__11=11;
    public static final int T__14=14;
    public static final int T__13=13;
    public static final int T__10=10;
    public static final int IDENT=4;

        @Override
        public void reportError(RecognitionException e) {
            throw new IllegalArgumentException(e);
        }


    // delegates
    // delegators

    public PSDLexer() {;} 
    public PSDLexer(CharStream input) {
        this(input, new RecognizerSharedState());
    }
    public PSDLexer(CharStream input, RecognizerSharedState state) {
        super(input,state);

    }
    public String getGrammarFileName() { return "/Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g"; }

    // $ANTLR start "T__8"
    public final void mT__8() throws RecognitionException {
        try {
            int _type = T__8;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:20:6: ( 'U' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:20:8: 'U'
            {
            match('U'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__8"

    // $ANTLR start "T__9"
    public final void mT__9() throws RecognitionException {
        try {
            int _type = T__9;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:21:6: ( 'X' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:21:8: 'X'
            {
            match('X'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__9"

    // $ANTLR start "T__10"
    public final void mT__10() throws RecognitionException {
        try {
            int _type = T__10;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:22:7: ( 'F' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:22:9: 'F'
            {
            match('F'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__10"

    // $ANTLR start "T__11"
    public final void mT__11() throws RecognitionException {
        try {
            int _type = T__11;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:23:7: ( 'G' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:23:9: 'G'
            {
            match('G'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__11"

    // $ANTLR start "T__12"
    public final void mT__12() throws RecognitionException {
        try {
            int _type = T__12;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:24:7: ( '->' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:24:9: '->'
            {
            match("->"); 


            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__12"

    // $ANTLR start "T__13"
    public final void mT__13() throws RecognitionException {
        try {
            int _type = T__13;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:25:7: ( '\\u2192' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:25:9: '\\u2192'
            {
            match('\u2192'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__13"

    // $ANTLR start "T__14"
    public final void mT__14() throws RecognitionException {
        try {
            int _type = T__14;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:26:7: ( '|' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:26:9: '|'
            {
            match('|'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__14"

    // $ANTLR start "T__15"
    public final void mT__15() throws RecognitionException {
        try {
            int _type = T__15;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:27:7: ( '\\u2228' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:27:9: '\\u2228'
            {
            match('\u2228'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__15"

    // $ANTLR start "T__16"
    public final void mT__16() throws RecognitionException {
        try {
            int _type = T__16;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:28:7: ( '^' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:28:9: '^'
            {
            match('^'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__16"

    // $ANTLR start "T__17"
    public final void mT__17() throws RecognitionException {
        try {
            int _type = T__17;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:29:7: ( '&' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:29:9: '&'
            {
            match('&'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__17"

    // $ANTLR start "T__18"
    public final void mT__18() throws RecognitionException {
        try {
            int _type = T__18;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:30:7: ( '\\u2227' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:30:9: '\\u2227'
            {
            match('\u2227'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__18"

    // $ANTLR start "T__19"
    public final void mT__19() throws RecognitionException {
        try {
            int _type = T__19;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:31:7: ( '~' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:31:9: '~'
            {
            match('~'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__19"

    // $ANTLR start "T__20"
    public final void mT__20() throws RecognitionException {
        try {
            int _type = T__20;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:32:7: ( '\\u00ac' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:32:9: '\\u00ac'
            {
            match('\u00AC'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__20"

    // $ANTLR start "T__21"
    public final void mT__21() throws RecognitionException {
        try {
            int _type = T__21;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:33:7: ( '[' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:33:9: '['
            {
            match('['); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__21"

    // $ANTLR start "T__22"
    public final void mT__22() throws RecognitionException {
        try {
            int _type = T__22;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:34:7: ( ']' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:34:9: ']'
            {
            match(']'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__22"

    // $ANTLR start "T__23"
    public final void mT__23() throws RecognitionException {
        try {
            int _type = T__23;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:35:7: ( '(' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:35:9: '('
            {
            match('('); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__23"

    // $ANTLR start "T__24"
    public final void mT__24() throws RecognitionException {
        try {
            int _type = T__24;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:36:7: ( ')' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:36:9: ')'
            {
            match(')'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__24"

    // $ANTLR start "T__25"
    public final void mT__25() throws RecognitionException {
        try {
            int _type = T__25;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:37:7: ( 'E' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:37:9: 'E'
            {
            match('E'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__25"

    // $ANTLR start "T__26"
    public final void mT__26() throws RecognitionException {
        try {
            int _type = T__26;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:38:7: ( 'A' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:38:9: 'A'
            {
            match('A'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__26"

    // $ANTLR start "T__27"
    public final void mT__27() throws RecognitionException {
        try {
            int _type = T__27;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:39:7: ( ',' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:39:9: ','
            {
            match(','); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__27"

    // $ANTLR start "T__28"
    public final void mT__28() throws RecognitionException {
        try {
            int _type = T__28;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:40:7: ( '$' )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:40:9: '$'
            {
            match('$'); 

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "T__28"

    // $ANTLR start "IDENT"
    public final void mIDENT() throws RecognitionException {
        try {
            int _type = IDENT;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:238:9: ( ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:238:11: ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
            {
            if ( (input.LA(1)>='A' && input.LA(1)<='Z')||(input.LA(1)>='a' && input.LA(1)<='z') ) {
                input.consume();

            }
            else {
                MismatchedSetException mse = new MismatchedSetException(null,input);
                recover(mse);
                throw mse;}

            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:238:30: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
            loop1:
            do {
                int alt1=2;
                int LA1_0 = input.LA(1);

                if ( ((LA1_0>='0' && LA1_0<='9')||(LA1_0>='A' && LA1_0<='Z')||LA1_0=='_'||(LA1_0>='a' && LA1_0<='z')) ) {
                    alt1=1;
                }


                switch (alt1) {
            	case 1 :
            	    // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:
            	    {
            	    if ( (input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z') ) {
            	        input.consume();

            	    }
            	    else {
            	        MismatchedSetException mse = new MismatchedSetException(null,input);
            	        recover(mse);
            	        throw mse;}


            	    }
            	    break;

            	default :
            	    break loop1;
                }
            } while (true);


            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "IDENT"

    // $ANTLR start "NUMBER"
    public final void mNUMBER() throws RecognitionException {
        try {
            int _type = NUMBER;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:239:10: ( ( '0' .. '9' )+ )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:239:12: ( '0' .. '9' )+
            {
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:239:12: ( '0' .. '9' )+
            int cnt2=0;
            loop2:
            do {
                int alt2=2;
                int LA2_0 = input.LA(1);

                if ( ((LA2_0>='0' && LA2_0<='9')) ) {
                    alt2=1;
                }


                switch (alt2) {
            	case 1 :
            	    // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:239:12: '0' .. '9'
            	    {
            	    matchRange('0','9'); 

            	    }
            	    break;

            	default :
            	    if ( cnt2 >= 1 ) break loop2;
                        EarlyExitException eee =
                            new EarlyExitException(2, input);
                        throw eee;
                }
                cnt2++;
            } while (true);


            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "NUMBER"

    // $ANTLR start "OPERATOR"
    public final void mOPERATOR() throws RecognitionException {
        try {
            int _type = OPERATOR;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:240:10: ( ( '!' | '@' | '#' | '%' | '*' | '-' | '+' | '=' | '\\\\' | ':' | ';' | '<' | '>' | '.' | '?' | '/' )+ )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:240:12: ( '!' | '@' | '#' | '%' | '*' | '-' | '+' | '=' | '\\\\' | ':' | ';' | '<' | '>' | '.' | '?' | '/' )+
            {
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:240:12: ( '!' | '@' | '#' | '%' | '*' | '-' | '+' | '=' | '\\\\' | ':' | ';' | '<' | '>' | '.' | '?' | '/' )+
            int cnt3=0;
            loop3:
            do {
                int alt3=2;
                int LA3_0 = input.LA(1);

                if ( (LA3_0=='!'||LA3_0=='#'||LA3_0=='%'||(LA3_0>='*' && LA3_0<='+')||(LA3_0>='-' && LA3_0<='/')||(LA3_0>=':' && LA3_0<='@')||LA3_0=='\\') ) {
                    alt3=1;
                }


                switch (alt3) {
            	case 1 :
            	    // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:
            	    {
            	    if ( input.LA(1)=='!'||input.LA(1)=='#'||input.LA(1)=='%'||(input.LA(1)>='*' && input.LA(1)<='+')||(input.LA(1)>='-' && input.LA(1)<='/')||(input.LA(1)>=':' && input.LA(1)<='@')||input.LA(1)=='\\' ) {
            	        input.consume();

            	    }
            	    else {
            	        MismatchedSetException mse = new MismatchedSetException(null,input);
            	        recover(mse);
            	        throw mse;}


            	    }
            	    break;

            	default :
            	    if ( cnt3 >= 1 ) break loop3;
                        EarlyExitException eee =
                            new EarlyExitException(3, input);
                        throw eee;
                }
                cnt3++;
            } while (true);


            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "OPERATOR"

    // $ANTLR start "WS"
    public final void mWS() throws RecognitionException {
        try {
            int _type = WS;
            int _channel = DEFAULT_TOKEN_CHANNEL;
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:247:7: ( ( ' ' | '\\t' )+ )
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:247:9: ( ' ' | '\\t' )+
            {
            // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:247:9: ( ' ' | '\\t' )+
            int cnt4=0;
            loop4:
            do {
                int alt4=2;
                int LA4_0 = input.LA(1);

                if ( (LA4_0=='\t'||LA4_0==' ') ) {
                    alt4=1;
                }


                switch (alt4) {
            	case 1 :
            	    // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:
            	    {
            	    if ( input.LA(1)=='\t'||input.LA(1)==' ' ) {
            	        input.consume();

            	    }
            	    else {
            	        MismatchedSetException mse = new MismatchedSetException(null,input);
            	        recover(mse);
            	        throw mse;}


            	    }
            	    break;

            	default :
            	    if ( cnt4 >= 1 ) break loop4;
                        EarlyExitException eee =
                            new EarlyExitException(4, input);
                        throw eee;
                }
                cnt4++;
            } while (true);

            skip();

            }

            state.type = _type;
            state.channel = _channel;
        }
        finally {
        }
    }
    // $ANTLR end "WS"

    public void mTokens() throws RecognitionException {
        // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:8: ( T__8 | T__9 | T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | IDENT | NUMBER | OPERATOR | WS )
        int alt5=25;
        alt5 = dfa5.predict(input);
        switch (alt5) {
            case 1 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:10: T__8
                {
                mT__8(); 

                }
                break;
            case 2 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:15: T__9
                {
                mT__9(); 

                }
                break;
            case 3 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:20: T__10
                {
                mT__10(); 

                }
                break;
            case 4 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:26: T__11
                {
                mT__11(); 

                }
                break;
            case 5 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:32: T__12
                {
                mT__12(); 

                }
                break;
            case 6 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:38: T__13
                {
                mT__13(); 

                }
                break;
            case 7 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:44: T__14
                {
                mT__14(); 

                }
                break;
            case 8 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:50: T__15
                {
                mT__15(); 

                }
                break;
            case 9 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:56: T__16
                {
                mT__16(); 

                }
                break;
            case 10 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:62: T__17
                {
                mT__17(); 

                }
                break;
            case 11 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:68: T__18
                {
                mT__18(); 

                }
                break;
            case 12 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:74: T__19
                {
                mT__19(); 

                }
                break;
            case 13 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:80: T__20
                {
                mT__20(); 

                }
                break;
            case 14 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:86: T__21
                {
                mT__21(); 

                }
                break;
            case 15 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:92: T__22
                {
                mT__22(); 

                }
                break;
            case 16 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:98: T__23
                {
                mT__23(); 

                }
                break;
            case 17 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:104: T__24
                {
                mT__24(); 

                }
                break;
            case 18 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:110: T__25
                {
                mT__25(); 

                }
                break;
            case 19 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:116: T__26
                {
                mT__26(); 

                }
                break;
            case 20 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:122: T__27
                {
                mT__27(); 

                }
                break;
            case 21 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:128: T__28
                {
                mT__28(); 

                }
                break;
            case 22 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:134: IDENT
                {
                mIDENT(); 

                }
                break;
            case 23 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:140: NUMBER
                {
                mNUMBER(); 

                }
                break;
            case 24 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:147: OPERATOR
                {
                mOPERATOR(); 

                }
                break;
            case 25 :
                // /Users/martijn/svn/ALIVEclipse workspace/net.sf.ictalive.operetta.psdeditor/ANTLR/PSD.g:1:156: WS
                {
                mWS(); 

                }
                break;

        }

    }


    protected DFA5 dfa5 = new DFA5(this);
    static final String DFA5_eotS =
        "\1\uffff\1\32\1\33\1\34\1\35\1\30\14\uffff\1\37\1\40\12\uffff\1"+
        "\41\3\uffff";
    static final String DFA5_eofS =
        "\42\uffff";
    static final String DFA5_minS =
        "\1\11\4\60\1\76\14\uffff\2\60\12\uffff\1\41\3\uffff";
    static final String DFA5_maxS =
        "\1\u2228\4\172\1\76\14\uffff\2\172\12\uffff\1\134\3\uffff";
    static final String DFA5_acceptS =
        "\6\uffff\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1"+
        "\21\2\uffff\1\24\1\25\1\26\1\27\1\30\1\31\1\1\1\2\1\3\1\4\1\uffff"+
        "\1\22\1\23\1\5";
    static final String DFA5_specialS =
        "\42\uffff}>";
    static final String[] DFA5_transitionS = {
            "\1\31\26\uffff\1\31\1\30\1\uffff\1\30\1\25\1\30\1\12\1\uffff"+
            "\1\20\1\21\2\30\1\24\1\5\2\30\12\27\7\30\1\23\3\26\1\22\1\3"+
            "\1\4\15\26\1\1\2\26\1\2\2\26\1\16\1\30\1\17\1\11\2\uffff\32"+
            "\26\1\uffff\1\7\1\uffff\1\14\55\uffff\1\15\u20e5\uffff\1\6\u0094"+
            "\uffff\1\13\1\10",
            "\12\26\7\uffff\32\26\4\uffff\1\26\1\uffff\32\26",
            "\12\26\7\uffff\32\26\4\uffff\1\26\1\uffff\32\26",
            "\12\26\7\uffff\32\26\4\uffff\1\26\1\uffff\32\26",
            "\12\26\7\uffff\32\26\4\uffff\1\26\1\uffff\32\26",
            "\1\36",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "\12\26\7\uffff\32\26\4\uffff\1\26\1\uffff\32\26",
            "\12\26\7\uffff\32\26\4\uffff\1\26\1\uffff\32\26",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "\1\30\1\uffff\1\30\1\uffff\1\30\4\uffff\2\30\1\uffff\3\30\12"+
            "\uffff\7\30\33\uffff\1\30",
            "",
            "",
            ""
    };

    static final short[] DFA5_eot = DFA.unpackEncodedString(DFA5_eotS);
    static final short[] DFA5_eof = DFA.unpackEncodedString(DFA5_eofS);
    static final char[] DFA5_min = DFA.unpackEncodedStringToUnsignedChars(DFA5_minS);
    static final char[] DFA5_max = DFA.unpackEncodedStringToUnsignedChars(DFA5_maxS);
    static final short[] DFA5_accept = DFA.unpackEncodedString(DFA5_acceptS);
    static final short[] DFA5_special = DFA.unpackEncodedString(DFA5_specialS);
    static final short[][] DFA5_transition;

    static {
        int numStates = DFA5_transitionS.length;
        DFA5_transition = new short[numStates][];
        for (int i=0; i<numStates; i++) {
            DFA5_transition[i] = DFA.unpackEncodedString(DFA5_transitionS[i]);
        }
    }

    class DFA5 extends DFA {

        public DFA5(BaseRecognizer recognizer) {
            this.recognizer = recognizer;
            this.decisionNumber = 5;
            this.eot = DFA5_eot;
            this.eof = DFA5_eof;
            this.min = DFA5_min;
            this.max = DFA5_max;
            this.accept = DFA5_accept;
            this.special = DFA5_special;
            this.transition = DFA5_transition;
        }
        public String getDescription() {
            return "1:1: Tokens : ( T__8 | T__9 | T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | IDENT | NUMBER | OPERATOR | WS );";
        }
    }
 

}